version: '3'

services:
  accounts_test:
    build:
      context: ./accounts
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache_test
    volumes:
      - ./accounts/src:/app/src
      - ./accounts/config:/app/config
      - ./accounts/.babelrc:/app/.babelrc
    environment:
      - NODE_ENV=test
    networks: 
      - test_net

  api-gateway_test:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - ./api-gateway/src:/app/src
      - ./api-gateway/.babelrc:/app/.babelrc
    environment:
      - NODE_ENV=test
      - VIRTUAL_HOST=api-test.nightfall.docker
    networks: 
      - test_net

  offchain_test:
    build:
      context: ./offchain
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache_test
    volumes:
      - ./offchain/src:/app/src
      - ./offchain/response:/app/response
      - ./offchain/build-test:/app/build
      - ./offchain/.babelrc:/app/.babelrc
      - ./offchain/__tests__:/app/__tests__
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./config:/app/config
    environment:
      - NODE_ENV=test
    networks: 
      - test_net

  zkp_test:
    build:
      context: ./zkp
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - ganache_test
    volumes:
      - ./zkp/src:/app/src
      - ./zkp/response:/app/response
      - ./zkp/build-test:/app/build
      - ./zkp/code:/app/code
      - ./zkp/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./zkp/__tests__:/app/__tests__
      - ./config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=test
    networks: 
      - test_net

  ganache_test:
    image: trufflesuite/ganache-cli:latest
    command: ganache-cli --accounts=10 --defaultBalanceEther=1000
    ports:
      - 8546:8545
    networks: 
      - test_net

  database_test:
    build:
      context: ./database
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      - mongo_test
    volumes:
      - ./database/src:/app/src
      - ./database/.babelrc:/app/.babelrc
      - ./zkp-utils:/app/node_modules/zkp-utils
      - ./config:/app/config
      - ./database/setup-mongo-acl-for-new-users.js:/app/setup-mongo-acl-for-new-users.js
    environment:
      - NODE_ENV=test
    networks: 
      - test_net

  mongo_test:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=nightfall_test
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mongo_volume_test:/data/db
    networks: 
      - test_net

  truffle-offchain_test:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache_test
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./offchain/contracts:/truffle/contracts:delegated
      - ./offchain/migrations/:/truffle/migrations:delegated
      - ./offchain/build-test/contracts/:/truffle/build/contracts:cached
      - ./offchain/test/:/truffle/test:delegated
    depends_on:
      - ganache_test
    logging:
      options:
        max-size: 10m
    networks: 
      - test_net

  truffle-zkp_test:
    image: ajmay/truffle:5.0.9
    environment:
      SOLC_VERSION: 0.5.8
      ETH_HOST: ganache_test
      ETH_GAS: 6000000
      ETH_GAS_PRICE: 20000000000
    volumes:
      - ./zkp/contracts/:/truffle/contracts:delegated
      - ./zkp/migrations/:/truffle/migrations:delegated
      - ./zkp/build-test/contracts/:/truffle/build/contracts:cached
      - ./zkp/test/:/truffle/test:delegated
      - ./zkp/src/:/truffle/src:delegated
    depends_on:
      - ganache_test
    logging:
      options:
        max-size: 10m
    networks: 
      - test_net

volumes:
  mongo_volume_test: {}
  zkp_code_test:
    driver: local
    driver_opts:
      type: none
      device: $PWD/zkp/code/
      o: bind

networks:
  test_net:
    driver: bridge
    ipam:
      driver: default

